{{- if .Values.clientApp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "client-app.serviceAccountName" . }}
  labels:
    {{- include "client-app.labels" . | nindent 4 }}
  {{- with .Values.clientApp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.clientApp.serviceAccount.automount }}
{{- end }}
