{{- if .Values.celery.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: celery-hpa
  labels:
    {{- include "celery.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: celery
  minReplicas: {{ .Values.celery.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.celery.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.celery.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.celery.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.celery.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.celery.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
